/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'orderDate' : Time,
  'buyer' : Principal,
  'product' : ProductId,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'quantity' : bigint,
  'image' : ExternalBlob,
  'price' : bigint,
  'farmer' : Principal,
}
export type ProductId = bigint;
export interface Review {
  'id' : ReviewId,
  'comment' : string,
  'buyer' : Principal,
  'rating' : bigint,
  'product' : ProductId,
}
export type ReviewId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminGetAllOrders' : ActorMethod<[], Array<Order>>,
  'adminGetAllProducts' : ActorMethod<[], Array<Product>>,
  'adminGetAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, bigint, bigint, string, ExternalBlob],
    ProductId
  >,
  'createReview' : ActorMethod<[ProductId, bigint, string], ReviewId>,
  'deleteFiles' : ActorMethod<[Array<string>], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrdersByBuyer' : ActorMethod<[Principal], Array<Order>>,
  'getOrdersByFarmer' : ActorMethod<[], Array<Order>>,
  'getProductsByFarmer' : ActorMethod<[Principal], Array<Product>>,
  'getProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getReviewsByProduct' : ActorMethod<[ProductId], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[ProductId], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, bigint, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];